### ISSUE TITLE
[Feature Request] ACS summary files?

### ISSUE THREAD

**Issue by tomshaffner** [jtleider/censusdata#14]
I'm trying to get ACS feature summary files, for example, table S1701 (https://data.census.gov/cedsci/table?q=percent%20poverty&hidePreview=false&tid=ACSST5Y2015.S1701&t=Poverty&vintage=2018) which has summary statistics on poverty rates. I seem to be unable to pull this via censusdata however; I've tried searching in a variety of ways and am unable to find this via the library.

I initially thought this was an error, but looking on the main page of the repo I don't see mention of ACS summary tables making me think the summary tables simply aren't included yet. Thus I'm writing here to ask if there's any plan to do so and when that might happen?

Or alternatively, am I doing something wrong in not being able to pull them?

**Comment by jtleider** [comment]
The subject tables can be downloaded using this package, as noted in the documentation, which may be helpful on this point ([https://jtleider.github.io/censusdata/variables.html](https://jtleider.github.io/censusdata/variables.html)). The examples in the documentation don't specifically cover the subject tables, but you should be able to download data from them in the same way as for other tables such as the detail or data profile tables. Please note that censusdata is not written to download data table by table; instead, you must find the variables you are interested in from a given table(s) (which can be all of them), and then specify those for download.
