### ISSUE TITLE
Unknown table type for variable C24010 when using censusvar

### ISSUE THREAD

**Issue by arivera007** [jtleider/censusdata#19]
Hello,

I put the wrong title: Title should be: `Unknown table type for variable C24010! `

   Thank you for this package. I am having trouble getting data for the table `C24010` when trying to use:
```
censusdata.censusvar('acs5','2018', ['C24010'])
```

When I look at the code, I see there is no way to pass that validation section. Is there a way to do it?

<img width="822" alt="Screen Shot 2020-10-27 at 12 12 02 PM" src="https://user-images.githubusercontent.com/979717/97337507-5fe08f00-184e-11eb-9973-5ca4129bb432.png">

**Comment by jtleider** [comment]
I have fixed this issue. Note that censusvar provides information on a single variable; an example call would be `censusdata.censusvar('acs5', 2018, ['C24010_001E'])`
