### ISSUE TITLE
Support for 2015-2019 ACS 5-Year Estimates

### ISSUE THREAD

**Issue by miaojingang** [jtleider/censusdata#20]
Thanks for developing this package, which has made my data pulls so much easier.

The Census Bureau has justed released the 2015-2019 5-year estimates. Is it possible to add support for that?

https://www.census.gov/programs-surveys/acs/news/updates.2020.html

**Comment by jtleider** [comment]
I'm glad you find it useful! This support has been added in version 1.11.

**Comment by miaojingang** [comment]
You are awesome! Thanks so much!
