### ISSUE TITLE
[feature] Display error messages with raise statements, instead of print()

### ISSUE THREAD

**Issue by adunmore** [jtleider/censusdata#21]
When errors are raised, the accompanying messages are output via print statements. This means that messages are printed at the top of the stack trace, where they're relatively hidden. Rather, error messages should be printed with the raise statement, as in `raise SomeError('Some error message')`

In my experience, this is especially confusing to less-experienced Python users, who aren't in the habit of scrolling through a stack trace, and so are unlikely to find these error messages.

The current approach:

```python
print('Some error message')
raise SomeError
```

The suggested approach:
```python
raise SomeError('Some error message')
```

**Comment by adunmore** [comment]
I suppose this isn't quite a feature request? More of a fix... Anyway, see my PR. I'm happy to make any changes to it!

**Comment by jtleider** [comment]
Thanks for the suggestion! I have implemented this in the most recent commit.
