### ISSUE TITLE
Wrong Python version requirement

### ISSUE THREAD

**Issue by zoharby** [jtleider/censusdata#24]
The following is used in setup.py:
`python_requires='>=2.7, >=3',`
The comma is equivalent to an and operator (see [here](https://www.python.org/dev/peps/pep-0440/#version-specifiers)), so this effectively implies python >= 3. 

The correct way would simply be:
`python_requires='>=2.7',`

**Comment by jtleider** [comment]
Thank you for pointing this out. I have fixed this in the current version.
