### ISSUE TITLE
sf1 variables

### ISSUE THREAD

**Issue by alexanderamy** [jtleider/censusdata#28]
Been having an issue downloading SF1 data. Seems like variable names have changed since last commit on sf1_2010_variables.json (e.g. P0030001 is now P003001 per https://api.census.gov/data/2010/dec/sf1/variables.json). Would it be possible to update that file?

Thanks for all your work here Julien!

**Comment by jtleider** [comment]
Sure thing! I pulled in the latest variable info in the latest version.
