### ISSUE TITLE
CensusData request takes too long

### ISSUE THREAD

**Issue by marlon-shiftone** [jtleider/censusdata#38]
I'm getting some census data by using the CensusData API. I'm looking for all variables related to each zip code from a list. However, it is taking too long, like 22601.822241067886 seconds per request. Would there be any workaround for this?

**Comment by jtleider** [comment]
Issues with the request time are outside the scope of this package. My only suggestion would be to try downloading fewer variables at a time, or downloading data for fewer zip codes at a time.
