### ISSUE TITLE
Census API Key

### ISSUE THREAD

**Issue by DieselAnalytics** [jtleider/censusdata#4]
Hello All,

This is not really an issue but I am trying to get understanding. The "key" argument is optional for census.download. Why would you need a key? Are you limited to the amount of data you can download without a Census API key?

Thanks in advance.

Regards,

Ryan

**Comment by jtleider** [comment]
Hello Ryan,

Yes, a limit applies if you do not use a key. Per the [Census Data API User Guide](https://www.census.gov/data/developers/guidance/api-user-guide.Query_Components.html):

You can include up to 50 variables in a single API query and can make up to 500 queries per IP address per day. More than 500 queries per IP address per day requires that you register for a Census key. That key will be part of your data request URL string.

Best,
Julien
