### ISSUE TITLE
-222222222, or -666666666 Variable Values

### ISSUE THREAD

**Issue by johnziebro** [jtleider/censusdata#41]
Question rather than an issue:

What do values such as  -222222222, or -666666666 for variables mean? I've run a web search and browsed US Census website but haven't located documentation on this. Any help would be appreciated.

**Comment by johnziebro** [comment]
I was able to locate this US Census PDF with API instructions which demonstrates replacing the values with an arbitrary value, but do not describe what they signify.

https://www2.census.gov/data/api-documentation/how-to-download-all-zip-code-tabulation-areas-from-the-census-api.pdf

**Comment by jtleider** [comment]
I would refer to the annotation fields for more information. I believe these vary by dataset, but as an example, here is information on them for the ACS 1-year data: [https://www.census.gov/data/developers/data-sets/acs-1year/data-notes.html](https://www.census.gov/data/developers/data-sets/acs-1year/data-notes.html)

**Comment by johnziebro** [comment]
Thank you for the direction.
