### ISSUE TITLE
Calling 50 or more variables in a single query

### ISSUE THREAD

**Issue by PFurst2000** [jtleider/censusdata#7]
The current Census API does not allow calling 50 or more variables in a single query. Is there a solution to takes a list of variable names, and collect them into chunks with no more than 50 variables, thereby calling 50+ variables in a single query? An example of a solution in R for this issue is described at: https://rstudio-pubs-static.s3.amazonaws.com/19337_2e7f827190514c569ea136db788ce850.html

**Comment by PFurst2000** [comment]
50+ calls may be performed by creating multiple calls with under 50 variables  and then joining the downloaded dataframes using merge_df

Example: merge_df = pd.merge(df1, df2, left_index=True, right_index=True)

**Comment by jtleider** [comment]
Thanks for the suggestion, I have updated the package to accommodate downloading an unlimited number of variables at a time by chunking.

**Comment by jtleider** [comment]
Great, glad it's helpful!

**Comment by PFurst2000** [comment]
Hi Julien,

I am looking to revise the attached Variable Info code to handle queries
from 1990 and 2000 SF3 and SF1 files.  Within the code the statement of
presrc = 'dec/'  currently exists for ACS and 2010 SF1 queries. I need to
revise the code so that presrc = null for 1990 and 2000 queries because
dec/ is not part of the API web address for pre-2010 census data. So far
revisions using code such as the following have all failed. Any
suggestions?
elif (src == 'sf1' or src == 'sf3') and year <= 2010: presrc = ''
elif (src == 'sf1' or src == 'sf3') and year <= 2010: presrc = None
 (edited)

  I understand that it may be a large undertaking to revise the code for
your publicly available python package. If so, I would like to customize
the package for my own personal use.

**Comment by jtleider** [comment]
Hi,

Are you revising the censusvar function? presrc should be automatically set to an empty string if src is 'sf3' (see line 44), so I don't think this is your problem, at least not for SF3. If my framework for constructing the URL is not working in this case, you can revise line 45 itself.

Thank you,
Julien

**Comment by PFurst2000** [comment]
I finally had some extra time to work with this again and I found that I
cant seem to be able to change the code from the variable_info.py file to
run SF1 samples from the 1990 and 2000 datasets. As you previously
mentioned, there is no issue running the code with the SF3 sample.

Original Code:
if (src == 'acs1' or src == 'acs5' or src == 'acsse') and year >= 2010:
presrc = 'acs/'
elif src == 'sf1': presrc = 'dec/'
else: presrc = ''

Proposed Code
if (src == 'acs1' or src == 'acs5' or src == 'acsse') and year >= 2010:
presrc = 'acs/'
elif (src == 'sf1' and year >= 2010): presrc = 'dec/'
elif [(src == 'sf1' or src == 'sf3')  and year <= 2010]: presrc = ''
else: presrc = ''


Error from proposed code: dec/ is included in proposed code when it should
be omitted.

[image: image.png]

**Comment by jtleider** [comment]
It looks like the code above would set presrc = '' for 1990 and 2000 SF1 downloads. I am unclear on the error you are encountering. For me to be able to assist you, please clarify how you intend to call the function, the URL you want the function to go to, and the URL the function is going to with your modified code.

Also, please note there is a typo in your proposed code as year==2010 is included in both if conditions for src=='sf1'.
