### ISSUE TITLE
Collecting 2000 SF1 & SF3 Data

### ISSUE THREAD

**Issue by PFurst2000** [jtleider/censusdata#8]
Hi Julien,
Is there a reason why this tool is unable to collect 2000 or 1990 census data? Looks like the issue is with the api calling link where /dec/ is used in the address to collect SF1 2010 data whereas this section of the address is missing from the the address to collect SF1 2000 data.
broken link: https://api.census.gov/data/2000/dec/sf1?get=NAME,H001001&for=county:005&in=state:36):
working link: https://api.census.gov/data/2000/sf1/variables/H001001.json
It would be much appreciated if you could update the code to handle earlier census data. Thanks!

**Comment by jtleider** [comment]
Hi,

Thank you for the suggestion. I wrote the package to access data from the sources I am personally familiar with. Unfortunately, I do not have time to add support for earlier decennial census data, as there is a fair amount of additional work I do beyond selecting the correct URL, to ensure the code is working correctly.

Best,
Julien
