### ISSUE TITLE
Collecting 2010 SF1 Block Group Data Using Wildcard Values

### ISSUE THREAD

**Issue by PFurst2000** [jtleider/censusdata#9]
Would it be possible to revise the code to allow the use of wild card values (*) for calling block group data for the 2010 SF1? Currently one must prepare separate queries for each set of block groups located in a particular tract. It is fairly time consuming to do this for extracting all block groups within a county. I understand the problem is with the Census Bureau's system which allows the use of wild card queries for census tracts and census blocks but not block groups.

**Comment by jtleider** [comment]
I think the best way to do this is to loop over all the tracts in a given county and make separate calls to the download function. I added a params method to censusgeo objects to facilitate this. An example:

```
import pandas as pd
import censusdata
county = [('state', '16'), ('county', '003')] # change to county of interest
censusvars = ['P001001'] # change to variables of interest

tracts = censusdata.geographies(censusdata.censusgeo(county + [('tract', '*')]), 'sf1', 2010)
print(tracts)
data = list()
for name, tractgeo in tracts.items():
  blockgroup_wildcard = censusdata.censusgeo(tractgeo.params()+(('block group', '*'),))
  print('Downloading data for ', blockgroup_wildcard)
  data.append(censusdata.download('sf1', 2010, blockgroup_wildcard, censusvars))
data = pd.concat(data)
print(data)
```

**Comment by PFurst2000** [comment]
Thanks Julien. I will try this out and really appreciate your help!
